# Site settings
title: Gottwald Raumgestaltung
email: monika.gottwald@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gottwald Raumgestaltung. Monika Gottwald
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gottwald-raumgestaltung.de" # the base hostname & protocol for your site
twitter_username: 
github_username:  
sass:
  sass_dir: _sass
include: ['_pages']

# Build settings
kramdown:
  input: GFM
